version: "3"
services:
  my-app:
    image: 1e1699e0975d
    ports:
      - 3000:3000
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-vol:/data/db
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 8081:8081

volumes:
  mongo-vol:
    driver: local
